module.exports = {
  "CMPSC 100": {
    title: "Computational Expression ",
    description:
      "An introduction to the principles of computer science with an emphasis on creative expression through the medium of a programming language. Participating in hands-on activities that often require teamwork, students learn the computational structures needed to solve problems and produce computational artifacts which address these problems in real-world contexts. Students also learn how to organize and document a program's source code so that it effectively communicates with the intended users and maintainers. Additionally, the introduction includes an overview of the discipline of computer science and computational thinking. During a weekly laboratory session students use industry-grade technology to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["ME", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["Knowledge of elementary algebra"],
    },
    unlocks: ["CMPSC 101", "CMPSC 102", "CMPSC 300"],
    topics: [
      "Object-oriented programming (OOP)",
      "Teamwork",
      "Version control systems",
      "Integrated development environments (IDE)",
      "Iteration",
      "Python programming",
      "Functions",
      "GitHub Flow",
      "Markdown",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Python",
      },
      {
        iconType: "tool",
        title: "VSCode",
      },
      {
        iconType: "tool",
        title: "Git",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 104": {
    title: "Document Engineering",
    description:
      "An introduction to creation of effective documents and documentation using industry-standard approaches to creating and treating 'documentation as code.' Participating in project-based and hands-on activities, students create purpose-driven digital writing with special attention to forms, formats, and conventions expected of contemporary technical communication. Students also gain experience with creating collaborative and ethically-consistent content working in a team-based setting. During a weekly laboratory session students employ contemporary software tools to complete technical documentation projects, reporting on their results through both written reflections and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["HE", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["CMPSC 302"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 203": {
    title: "Software Engineering",
    description:
      "A human-centric study of the principles used during the engineering of high-quality software systems. In addition to examining the human behaviors and social processes undergirding software development methodologies, students participate in teams tasked with designing, developing, and delivering a significant software application for a customer. During a weekly laboratory session, students use state-of-the-art software engineering, management, and communication tools to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["SB", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 101"],
    },
    unlocks: ["CMPSC 404"],
    topics: [
      "Project Management",
      "Unit Testing",
      "Debugging",
      "Teamwork",
      "Integration Testing",
      "Fault Localization",
      "Version Control Systems",
      "Implementation",
      "Linting",
      "Technical Writing",
      "Software Design",
      "Static Analysis",
      "Performance Assessment",
      "Coverage Testing",
      "Dynamic Analysis",
      "Professional Communication",
      "Open Source Software",
      "User Studies",
      "Flow of Control",
      "Software Testing",
      "Code Review",
      "Requirements Gathering",
      "Mutation Testing",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Git",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "Markdown",
      },
      {
        iconType: "tool",
        title: "pytest",
      },
      {
        iconType: "tool",
        title: "Python",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 201": {
    title: "Programming Languages",
    description:
      "A study of the fundamental concepts that arise in different programming language paradigms. Students learn how programming languages are designed and implemented, and how these factors affect the overall usability, performance, and effectiveness of computer software. Participating in hands-on activities that often require teamwork, students gain experience in leveraging the styles and features of programming languages to implement and evaluate correct and efficient computer software. During a weekly laboratory session, students use state-of-the-art technology to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: ["CMPSC 101", "CMPSC 102"],
      allof: [],
    },
    unlocks: ["CMPSC 400", "CMPSC 403"],
    topics: [],
    technicalTopics: [
      "Language Design",
      "Compilation",
      "Interpretation",
      "Understanding Java",
      "Syntax",
      "Grammars",
      "Parsing",
      "Scoping",
      "Binding",
      "Storage Management",
      "Control Flow",
      "Functions",
      "Typing",
      "Language Paradigms",
      "Language Security",
    ],
    professionalTopics: ["teamwork", "code review", "communication"],
    tools: [
      {
        iconType: "tool",
        title: "C",
      },
      {
        iconType: "tool",
        title: "C++",
      },
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "Git",
      },
      {
        iconType: "tool",
        title: "Go",
      },
      {
        iconType: "tool",
        title: "Haskell",
      },
      {
        iconType: "tool",
        title: "Java",
      },
      {
        iconType: "tool",
        title: "Java Bytecode",
      },
      {
        iconType: "tool",
        title: "JavaScript",
      },
      {
        iconType: "tool",
        title: "Python",
      },
    ],
    lab: [],
    learningObjectives: [
      "Understand fundamental concepts that underlie programming language syntax and semantics",
      "Gain exposure to different languages and language paradigms",
      "Learn how to use language constructs effectively to design correct and elegant programs",
      "Continue developing team-working strategies",
      "Enhance ability to write and present ideas about software in a clear, concise, and compelling fashion",
    ],
    learningOutcomes: [
      "Can proficiently program in languages such as Java",
      "Able to design and understand a simple grammar for a language",
      "Able to implement a simple scanner",
      "Able to create a simple parser",
      "Be able to learn new programming languages with a minimum effort based on an understanding of general principles of language design and implementation",
    ],
  },
  "CMPSC 101": {
    title: "Data Structures ",
    description:
      "An exploration of technologies and data relationships which power modern web applications. Participating in hands-on activities which require teamwork, students build web applications that incorporate the full stack, including databases, application programming interfaces (APIs), and public-facing web pages or mobile applications. Students develop a broad knowledge of different development approaches, languages, and design paradigms to learn advantages and disadvantages of technologies and frameworks. During weekly laboratory sessions, students participate in iterative design processes and report progress and technical details through written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: ["CMPSC 100", "permission of the instructor."],
      allof: [],
    },
    unlocks: [
      "CMPSC 201",
      "CMPSC 202",
      "CMPSC 203",
      "CMPSC 301",
      "CMPSC 303",
      "CMPSC 304",
      "CMPSC 305",
      "CMPSC 350",
    ],
    topics: [
      "Teamwork",
      "Recursion",
      "Time Complexity",
      "Data Structures",
      "Object-oriented Programming",
      "Data Analysis",
      "Iteration",
      "Version Control Systems",
      "Technical Writing",
      "Algorithms",
      "Statistical Analysis",
      "Software Design",
      "Continuous Deployment",
      "Flow of Control",
      "Computational Thinking",
      "Code Review",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "Java",
      },
      {
        iconType: "tool",
        title: "Git",
      },
      {
        iconType: "tool",
        title: "Linters",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "Markdown",
      },
      {
        iconType: "tool",
        title: "Gradle",
      },
      {
        iconType: "tool",
        title: "Travis CI",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 400": {
    title: "Operating Systems",
    description:
      "A study of the principles used in the design, implementation, and evaluation of operating systems. Participating in hands-on activities that often require teamwork, students create and assess components of an operating system that runs on modern computer hardware. Leveraging insights and tools from an industry partner, students also investigate the resource management, process scheduling, and file systems used in representative operating systems. During a weekly laboratory session students use advanced operating systems software to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: ["CMPSC 200", "CMPSC 201"],
      allof: [],
    },
    unlocks: [],
    topics: [
      "Teamwork",
      "Shells",
      "Interfaces - User Experience",
      "Version Control Systems",
      "Operating Systems",
      "Race Conditions",
      "Technical Writing",
      "Kernels",
      "Binaries",
      "Memory Management",
      "Interfaces - Devices",
      "Code Review",
      "Multithreading",
      "CPUs",
      "Semaphores",
      "Low-level Languages",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "GCC",
      },
      {
        iconType: "tool",
        title: "Github",
      },
      {
        iconType: "tool",
        title: "GatorGrader",
      },
      {
        iconType: "tool",
        title: "Discord",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "DOUBL 600": {
    title: "Sr Project I: Double Major",
    description:
      "Continuation of independent research in software engineering culminating in the development of and release of a computational artifact. Must be taken on the letter-grade basis. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "1 to 4",
    prerequisites: {
      anyof: ["Instructor-approved 580 equivalent", "CMPSC 580"],
      allof: [],
    },
    unlocks: ["DOUBL 600"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "DOUBL 610": {
    title: "Sr Project II: Double Major",
    description:
      "Independent research in software engineering culminating in the development of a prototype or early draft of a computational artifact. Must be taken on the letter-grade basis. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "1 to 4",
    prerequisites: {
      anyof: [],
      allof: ["DOUBL 600"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "SE 600": {
    title: "Senior Project I",
    description:
      "Independent research in software engineering culminating in the development of a prototype or early draft of a computational artifact. Must be taken on the letter-grade basis. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 580"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "SE 610": {
    title: "Senior Project II",
    description:
      "Continuation of independent research in software engineering culminating in the development of and release of a computational artifact. Must be taken on the letter-grade basis. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["SE 600"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 404": {
    title: "Web Applications",
    description:
      "An exploration of technologies and data relationships which power modern web applications. Participating in hands-on activities which require teamwork, students build web applications that incorporate the full stack, including databases, application programming interfaces (APIs), and public-facing web pages or mobile applications. Students develop a broad knowledge of different development approaches, languages, and design paradigms to learn advantages and disadvantages of technologies and frameworks. During weekly laboratory sessions, students participate in iterative design processes and report progress and technical details through written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 203", "CMPSC 302"],
    },
    unlocks: [],
    topics: ["APIs", "HTTP/S", "SSL", "Databases", "TCP/IP"],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "PHP",
      },
      {
        iconType: "tool",
        title: "React",
      },
      {
        iconType: "tool",
        title: "Javascript",
      },
      {
        iconType: "tool",
        title: "Nodejs",
      },
      {
        iconType: "tool",
        title: "HTML",
      },
      {
        iconType: "tool",
        title: "CSS",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 580": {
    title: "Junior Seminar",
    description:
      "An investigation of select topics in computer and information science that prepares students for the completion of a senior project with the purpose of identifying knowledge gaps in the discipline. Students learn how to read scholarly papers, state and motivate research questions, create a software prototype or develop scholarly artifacts to address their findings, and collect and organize evidence for evaluating the outcome of their project. During a weekly laboratory session students use industry-grade technology to gain practical skills in technical writing, the presentation of technical concepts, and the production of an artifact. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [
      "Planning",
      "Idea Development",
      "Professional Development",
      "Literature Review",
      "User Studies",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "Latex",
      },
      {
        iconType: "tool",
        title: "GatorGrader",
      },
      {
        iconType: "tool",
        title: "Python",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "R",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 403": {
    title: "Computer Security",
    description:
      "A study of the principles used in the design, implementation, and evaluation of secure computer hardware and software. Participating in hands-on activities that often require teamwork, students assess the trade-offs in security policies and create software with efficient and effective security mechanisms. Leveraging insights and tools from an industry partner, students also investigate techniques for providing access control, secure channels, and intrusion detection. During a weekly laboratory session students use advanced security software to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: ["CMPSC 200", "CMPSC 201"],
      allof: [],
    },
    unlocks: [],
    topics: [
      "Privacy",
      "Security",
      "Threat Modelling",
      "Networking",
      "Malware",
      "Ethics, Policy",
      "Cryptography",
      "Firewalls",
      "Memory Safety",
      "Cryptanalysis",
      "Encryption",
      "Security Economics",
      "Virtual Private Networks",
      "Buffer Overflow",
      "Authentication",
      "Ethical Hacking",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "C",
      },
      {
        iconType: "tool",
        title: "GO",
      },
      {
        iconType: "tool",
        title: "HTML",
      },
      {
        iconType: "tool",
        title: "Rust",
      },
      {
        iconType: "tool",
        title: "JavaScript",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 305": {
    title: "Database Systems",
    description:
      "A study of the application and evaluation of database management systems. Participating in hands-on activities that often require teamwork, students design, implement, and deploy database systems that store interdisciplinary data sets. In addition to learning how to develop and assess interfaces for databases, students study the efficiency and effectiveness of alternative data management systems. During a weekly laboratory session students use industry-grade technology to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 101"],
    },
    unlocks: [],
    topics: [
      "Teamwork",
      "Queries",
      "Version Control Systems",
      "Databases",
      "Ethics",
      "Data Modeling",
      "Data Storage",
      "Code Review",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Apache Cassandra",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "SQL",
      },
      {
        iconType: "tool",
        title: "Django",
      },
      {
        iconType: "tool",
        title: "MongoDB",
      },
      {
        iconType: "tool",
        title: "SQLite",
      },
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "Neo4j",
      },
      {
        iconType: "tool",
        title: "GatorGrader",
      },
      {
        iconType: "tool",
        title: "Python",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 302": {
    title: "Web Development",
    description:
      "An exploration of technologies and data relationships which power modern web applications. Participating in hands-on activities which require teamwork, students build web applications that incorporate the “full stack,” including databases, application programming interfaces (APIs), and public-facing web pages or mobile applications. Students develop a broad knowledge of different development approaches, languages, and design paradigms to learn advantages and disadvantages of technologies and frameworks. During weekly laboratory sessions, students participate in iterative design processes and report progress and technical details through written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["IP", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 104"],
    },
    unlocks: ["CMPSC 404"],
    topics: [
      "Teamwork",
      "Responsive Design",
      "Iterative Design",
      "Computer Graphics",
      "Networking",
      "User Studies",
      "Version Control Systems",
      "Professional Communication",
      "UI/UX",
      "Design Thinking",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "React",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "11ty",
      },
      {
        iconType: "tool",
        title: "CSS",
      },
      {
        iconType: "tool",
        title: "HTML",
      },
      {
        iconType: "tool",
        title: "Figma",
      },
      {
        iconType: "tool",
        title: "Netlify",
      },
      {
        iconType: "tool",
        title: "JavaScript",
      },
      {
        iconType: "tool",
        title: "Markdown",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 303": {
    title: "Artificial Intelligence",
    description:
      "A study of the design and implementation of intelligent computer systems that can learn, plan, and solve problems autonomously. In addition to examining techniques for designing intelligent software agents, students investigate the social, political, and ethical implications of intelligent systems. Through hands-on activities that often require team-work, students explore the application of artificial intelligence methods in areas such as computer vision, natural language processing, and video game development. During a weekly laboratory session students use industry-grade technology to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: ["CMPSC 101", "CMPSC 102"],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [
      "Agents",
      "Search Algorithms in AI",
      "Learning Overview",
      "Supervised Learning",
      "Computer Vision",
      "Natural Language Processing",
      "Bayes Theory",
      "Neural Networks",
      "Attention Mechanisms",
      "Transformers",
      "Prompt Engineering",
    ],
    professionalTopics: ["teamwork", "code review", "communication"],
    tools: [
      {
        iconType: "tool",
        title: "Arduino",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "Tensoflow",
      },
      {
        iconType: "tool",
        title: "Keras",
      },
      {
        iconType: "tool",
        title: "Python",
      },
      {
        iconType: "tool",
        title: "Google Colab",
      },
      {
        iconType: "tool",
        title: "GPT",
      },
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "OpenCV",
      },
      {
        iconType: "tool",
        title: "NLTK",
      },
    ],
    lab: [],
    learningObjectives: [
      "Understand foundational principles that drive the field of artificial intelligence",
      "Practice implementing intelligent applications",
      "Investigate social problems around AI including ethical concerns and environmental challenges",
      "Learn how to determine when an AI approach is appropriate for a given situation, be able to select and implement an AI method for it",
      "Learn to evaluate the developed AI systems while considering their social, political and ethical implications",
    ],
    learningOutcomes: [
      "Can create a simple agent using Arduino board and sensors",
      "Able to apply search algorithm to solve an agent-based problem",
      "Can design, implement and assess an intelligent system for a computer vision application using supervised learning",
      "Can design, implement and assess an intelligent system for a natural language processing application using deep neural networks",
      "Can effectively reflect on ethical, political and social issues surrounding AI",
    ],
  },
  "CMPSC 529": {
    title: "Internship",
    description:
      "Academic study completed in support of an internship experience with a partner institution. An Allegheny faculty member assigns and evaluates the academic work done by the student. May be repeated for credit. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "1-4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 600": {
    title: "Senior Thesis I",
    description:
      "Individual research under the guidance of a member of the Department's faculty. A project proposal must be submitted to the Department and approved in the semester prior to the semester in which the student intends to register for the course. May be repeated for credit. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "2",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 580"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 610": {
    title: "Senior Project II",
    description:
      "Continuation of independent research in computer science culminating in the development of and release of a computational artifact. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "2",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 600"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
};
