export default {
  "Informatics Major": {
    title: "Informatics Major",
    description:
      "Because this program is Interdisciplinary Studies, students who major in Informatics may complete any minor to satisfy the college requirement that the major and minor be in different areas of study. However, students who major in Informatics may not double-major or minor in Computer Science, Data Science, or Software Engineering. The Informatics major leads to the Bachelor of Arts or the Bachelor of Science degree (students may elect to receive either degree) and requires a minimum of 48 semester credit hours. At most one of the foundation courses (CMPSC 100, CMPSC 101, or CMPSC 105) may be presented for the major on the Credit/No Credit grade basis. Courses with prerequisites are marked with an asterisk (*).",
    distributionRequirements: [],
    credits: "",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "book",
        title: "Allegheny College Computer Science Academic Bulletin",
        href: "https://www.cs.allegheny.edu/teaching/bulletin/#cmpsc",
      },
    ],
    platform: ["https://www.cs.allegheny.edu/"],
    learningObjectives: [],
    learningOutcomes: [],
  },
  Foundation: {
    title: "Informatics Major",
    description:
      "Because this program is Interdisciplinary Studies, students who major in Informatics may complete any minor to satisfy the college requirement that the major and minor be in different areas of study. However, students who major in Informatics may not double-major or minor in Computer Science, Data Science, or Software Engineering. The Informatics major leads to the Bachelor of Arts or the Bachelor of Science degree (students may elect to receive either degree) and requires a minimum of 48 semester credit hours. At most one of the foundation courses (CMPSC 100, CMPSC 101, or CMPSC 105) may be presented for the major on the Credit/No Credit grade basis. Courses with prerequisites are marked with an asterisk (*).",
    distributionRequirements: [],
    credits: "",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "book",
        title: "Allegheny College Computer Science Academic Bulletin",
        href: "https://www.cs.allegheny.edu/teaching/bulletin/#cmpsc",
      },
    ],
    platform: ["https://www.cs.allegheny.edu/"],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "Application Modules": {
    title: "Application Modules",
    description:
      "Choose a minimum of two courses (8 credits) from a minimum of one application module. Students should consult with an advisor to design their application module coursework in relation to their interests, questions, and goals, as well as their overall program of study.",
    distributionRequirements: [],
    credits: "",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    platform: ["https://www.cs.allegheny.edu/"],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 100": {
    title: "Computational Expression",
    description:
      "An introduction to the principles of computer science with an emphasis on creative expression through the medium of a programming language. Participating in hands-on activities that often require teamwork, students learn the computational structures needed to solve problems and produce computational artifacts which address these problems in real-world contexts. Students also learn how to organize and document a program's source code so that it effectively communicates with the intended users and maintainers. Additionally, the introduction includes an overview of the discipline of computer science and computational thinking. During a weekly laboratory session students use industry-grade technology to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["ME", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["Knowledge of elementary algebra"],
    },
    unlocks: ["CMPSC 101", "CMPSC 102", "CMPSC 300"],
    topics: [
      "Object-oriented programming (OOP)",
      "Teamwork",
      "Version control systems",
      "Integrated development environments (IDE)",
      "Iteration",
      "Python programming",
      "Functions",
      "GitHub Flow",
      "Markdown",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Python",
      },
      {
        iconType: "tool",
        title: "VSCode",
      },
      {
        iconType: "tool",
        title: "Git",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 300": {
    title: "Bioinformatics",
    description:
      "An introduction to the development and application of methods, from the computational and information sciences, for the investigation of biological phenomena. In this interdisciplinary course, students integrate computational techniques with biological knowledge to develop and use analytical tools for extracting, organizing, and interpreting information from genetic sequence data. Often participating in team-based and hands-on activities, students implement and apply useful bioinformatics algorithms. During a weekly laboratory session students employ cutting-edge software tools and programming environments to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: ["CMPSC 100", "BIO 221", "FSBIO 201"],
      allof: [],
    },
    unlocks: [],
    topics: [
      "Ethics",
      "Sequence Alignment",
      "Code Review",
      "Philosophy of Biology",
      "Databases",
      "Mathematical Programming",
      "Genetic Mutation",
      "Bioinformatics",
      "Gene Prediction",
      "Data Modeling",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "BLAST",
      },
      {
        iconType: "tool",
        title: "UniProt",
      },
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "GatorGrader",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 105": {
    title: "Data Exploration",
    description:
      "An introduction to the methods of collecting, exploring, transforming and visualizing data for storytelling. Often participating in team-based and hands-on activities, students learn how to use web platforms and dashboards to acquire, explore and investigate data to generate summarized key data insights using visual techniques. Students also apply open-source programming language to discover patterns in the data, test hypotheses, and check assumptions using graphical representations. During a weekly laboratory session, students employ cutting-edge software tools to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: ["Teamwork", "Data Structures", "Recursion"],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "Git",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 101": {
    title: "Data Abstraction",
    description:
      "An exploration of technologies and data relationships which power modern web applications. Participating in hands-on activities which require teamwork, students build web applications that incorporate the full stack, including databases, application programming interfaces (APIs), and public-facing web pages or mobile applications. Students develop a broad knowledge of different development approaches, languages, and design paradigms to learn advantages and disadvantages of technologies and frameworks. During weekly laboratory sessions, students participate in iterative design processes and report progress and technical details through written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: ["CMPSC 100", "permission of the instructor."],
      allof: [],
    },
    unlocks: [
      "CMPSC 201",
      "CMPSC 202",
      "CMPSC 203",
      "CMPSC 301",
      "CMPSC 303",
      "CMPSC 304",
      "CMPSC 305",
      "CMPSC 350",
    ],
    topics: [
      "Teamwork",
      "Recursion",
      "Time Complexity",
      "Data Structures",
      "Object-oriented Programming",
      "Data Analysis",
      "Iteration",
      "Version Control Systems",
      "Technical Writing",
      "Algorithms",
      "Statistical Analysis",
      "Software Design",
      "Continuous Deployment",
      "Flow of Control",
      "Computational Thinking",
      "Code Review",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "Java",
      },
      {
        iconType: "tool",
        title: "Git",
      },
      {
        iconType: "tool",
        title: "Linters",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "Markdown",
      },
      {
        iconType: "tool",
        title: "Gradle",
      },
      {
        iconType: "tool",
        title: "Travis CI",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 304": {
    title: "Robotic Agents",
    description:
      "A study of the design and implementation of autonomous software agents and robotic systems that cooperatively complete complex tasks. In addition to examining techniques for large-scale coordination and group-based decision-making, students learn how to apply the field's technologies to address the challenges facing local and global communities. Participating in hands-on activities that often require teamwork, students develop and evaluate several multi-agent or multi-robot systems, while also reflecting on the civic issues surrounding the use of these systems. During a weekly laboratory session students use state-of-the-art technology to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["CL", "QR"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 101", "CMPSC 102"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [
      "Ethical Robots",
      "Actuating",
      "Sensing",
      "Locomotion",
      "Modularity",
      "Navigation",
      "Robot Operating System",
      "Manipulation",
      "Mapping",
      "Learning in robotics",
    ],
    professionalTopics: [
      "community engagement",
      "teamwork",
      "code review",
      "communication",
    ],
    tools: [
      {
        iconType: "tool",
        title: "Python",
      },
      {
        iconType: "tool",
        title: "ROS",
      },
      {
        iconType: "tool",
        title: "Arduino",
      },
      {
        iconType: "tool",
        title: "Raspberri Pi",
      },
      {
        iconType: "tool",
        title: "Sensors",
      },
      {
        iconType: "tool",
        title: "Drones",
      },
      {
        iconType: "tool",
        title: "GoPiGo",
      },
      {
        iconType: "tool",
        title: "Turtlebot",
      },
      {
        iconType: "tool",
        title: "Git",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
    ],
    lab: [],
    learningObjectives: [
      "Understand the field of agent-based and robotic systems",
      "Gain exposure to multiple different robot platforms",
      "Design and develop several robot applications",
      "Learn about and reflect on public problems that involve robotic technology",
      "Participate in civic engagement activities",
    ],
    learningOutcomes: [
      "Able to design, implement, and test application for a wheeled robot",
      "Able to design, implement, and test application for a drone",
      "Able to design, implement, and test application for a robotic arm",
      "Can develop a simple application using ROS",
      "Can put together engaging demonstrations using robots for public events",
    ],
  },
  "CMPSC 350": {
    title: "Computational Narrative",
    description:
      "A study of the craft and deployment of procedurally-generated digital narratives, placing an emphasis on using data sources and computational methods as storytelling media. Students focus on critical, close reading of professional and student works while completing a single long-form work of their own. Topics include natural language processing (NLP), procedural illustration, computational constraint, and the development of conceptual documentary works.",
    distributionRequirements: ["HE", "ME"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 101"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 406": {
    title: "Internet Of Things",
    description:
      "An introduction to small-scale, purpose-built physical computational objects which embed sensors, integrate with networks, and process environmental signals. Exploring various industrial architectures, students develop devices that respond to physical stimuli and transmit data across networks to motivate additional device behavior and interactivity while considering human interaction design (HID) and “people-centered” principles that drive device design. During weekly laboratory sessions, students complete projects which focus on industry standards of data transmission and privacy in addition to optimizing device performance for real-time, high-availability applications. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["SP", "SB"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 200"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ART 187": {
    title: "Electronic & Intermedia Art",
    description:
      "An introduction to using electronic technologies/software and digital media as art-making tools. Emphasis on awareness of the elements of 2D design/composition and the vocabulary used to describe it. Coursework integrates effective oral and written communication to explore contemporary and historical practices within the medium and the role of electronic art in human experience. This course emphasizes the development of skills with a focus on technique, contemporary and historical issues, and conceptual development.",
    distributionRequirements: ["HE", "ME"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ART 287"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ART 287": {
    title: "Art at the Intersection of Science and Culture",
    description:
      "Application of the tools and technologies of biological science and computer science to create thought provoking and socially resonant works of art that broaden scientific literacy, while creatively exploring complex philosophical and conceptual ideas of where biology ends and technologies begin. Students use emerging and established trends to articulate ideas and create effective viewer experiences. Coursework integrates effective oral and written communication to explore contemporary and historical practices within the medium and the role of art in human experience.",
    distributionRequirements: ["HE", "ME"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["ART 187"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "COMM 376": {
    title: "Ethnographic Methods in Media and Cultural Studies",
    description:
      "A hands-on introduction to ethnographic research in media and cultural studies. Students learn methods of interviewing, oral history, and participant observation while engaging in collaborative, community-based research. Students work together to explore the ways in which media technologies shape cultures and use digital storytelling tools (e.g., podcasting) to share their collective research with a broader public.",
    distributionRequirements: ["CL", "HE"],
    credits: "4",
    prerequisites: {
      anyof: ["COMM 125", "COMM 145", "FSCOM 201"],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "FILM 187": {
    title: "Filmmaking & Digital Stories 1",
    description:
      "A study of aesthetic concepts and production techniques involved in cinematic and television production. Students create works that demonstrate an understanding of the various production elements and how they can be combined for effective communication.",
    distributionRequirements: ["HE", "ME"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["FILM 300"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ART 251": {
    title: "Contemporary Art Writing",
    description:
      "A study of modern and contemporary art through the lens of art writing. This course builds the research-based skills and visual literacy necessary for art writing--a rigorous but creative process of knowledge production. Art writers mobilize art in the service of broader cultural conversations to address social and political challenges, from race and gender equity to climate change. Students read and practice discipline-specific writing, and they also focus on interdisciplinary authors who posit art as a model of political resistance. Along with foundational writing skills, this course promotes proficiency in the visual and written language of contemporary art",
    distributionRequirements: ["HE", "PD"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ART 287"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ART 343": {
    title: "Feminist Art Histories",
    description:
      "An examination of the impact of feminism and feminist theory on visual culture from the 1960s to today, with select pre-1960s material as background. Visual culture encompasses academic Art History, but also popular spaces of representation including film, music, and television. Students learn how feminist cultural producers address systemic inequalities of gender, race, and class. Recognizing that categories of gender and sexuality are constructed differently across cultures, this course takes a transnational approach. There is focus on the intersections of feminism and post-human studies and the impact of new technology and climate on contemporary feminism, queer theory, and their art.",
    distributionRequirements: ["HE", "PD"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 110": {
    title: "Intro to Literary Studies",
    description:
      "A course in the close reading of literary texts. Through the study of multiple genres of literary works, students develop their ability to read carefully and to understand the relationship between literary texts and a range of historical and/or literary contexts. The course also introduces students to some of the terms and critical approaches necessary for further literary study.",
    distributionRequirements: ["HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ENGL 210", "ENGL 360"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 111": {
    title: "Literature and the Arts",
    description:
      "A course in the close reading of literary texts. Through the study of multiple genres of literary works, students develop their ability to read carefully and to understand the relationship between literary texts and a range of historical and/or literary contexts. The course also introduces students to some of the terms and critical approaches necessary for further literary study.",
    distributionRequirements: ["HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ENGL 210", "ENGL 360"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 112": {
    title: "Literature and the Body",
    description:
      "A course in the close reading of literary texts. Through the study of multiple genres of literary works, students develop their ability to read carefully and to understand the relationship between literary texts and a range of historical and/or literary contexts. The course also introduces students to some of the terms and critical approaches necessary for further literary study.",
    distributionRequirements: ["HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ENGL 210", "ENGL 360"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 113": {
    title: "Literature and Race",
    description:
      "A course in the close reading of literary texts. Through the study of multiple genres of literary works, students develop their ability to read carefully and to understand the relationship between literary texts and a range of historical and/or literary contexts. The course also introduces students to some of the terms and critical approaches necessary for further literary study.",
    distributionRequirements: ["HE", "PD"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ENGL 210", "ENGL 360"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 114": {
    title: "Literature and Business",
    description:
      "A course in the close reading of literary texts. Through the study of multiple genres of literary works, students develop their ability to read carefully and to understand the relationship between literary texts and a range of historical and/or literary contexts. The course also introduces students to some of the terms and critical approaches necessary for further literary study.",
    distributionRequirements: ["HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ENGL 210", "ENGL 360"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 115": {
    title: "Literature and Sexuality",
    description:
      "A course in the close reading of literary texts. Through the study of multiple genres of literary works, students develop their ability to read carefully and to understand the relationship between literary texts and a range of historical and/or literary contexts. The course also introduces students to some of the terms and critical approaches necessary for further literary study.",
    distributionRequirements: ["HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ENGL 210", "ENGL 360"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 116": {
    title: "Literature and the Environment",
    description:
      "A course in the close reading of literary texts. Through the study of multiple genres of literary works, students develop their ability to read carefully and to understand the relationship between literary texts and a range of historical and/or literary contexts. The course also introduces students to some of the terms and critical approaches necessary for further literary study.",
    distributionRequirements: ["HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ENGL 210", "ENGL 360"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 117": {
    title: "Literature and Science",
    description:
      "A course in the close reading of literary texts. Through the study of multiple genres of literary works, students develop their ability to read carefully and to understand the relationship between literary texts and a range of historical and/or literary contexts. The course also introduces students to some of the terms and critical approaches necessary for further literary study.",
    distributionRequirements: ["HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ENGL 210", "ENGL 360"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 118": {
    title: "Literature and the Mind",
    description:
      "A course in the close reading of literary texts. Through the study of multiple genres of literary works, students develop their ability to read carefully and to understand the relationship between literary texts and a range of historical and/or literary contexts. The course also introduces students to some of the terms and critical approaches necessary for further literary study.",
    distributionRequirements: ["HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: ["ENGL 210", "ENGL 360"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENGL 360": {
    title: "Language, Theory, and Practice",
    description:
      "A course that explores how language, reading, and writing operate as historical cultural practices, as subjects of theoretical study, and as effective contemporary communication. The emphasis of the course vary, depending on the instructor. Topics may include the cultural history of the English language, twentiethcentury literary and critical theory, and modes of communication in the digital age. May be repeated for credit",
    distributionRequirements: ["HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [
        "One 100-level literature course - Must be completed prior to taking this course.",
      ],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "HIST 170": {
    title: "Introduction to Public History",
    description:
      "An introduction to the theory and practice of public history, a collaborative approach to history that emphasizes inter-disciplinary methodology, oral history, and a variety of presentation formats to present historical projects that interact with audiences in the public sector. Through readings, discussions, viewing of films and documentaries, and field trips to museums and historic sites, students examine issues that confront historians working in public settings. Students work with specific archives and/or groups at Allegheny or elsewhere to create and and publish digital story-telling projects intended to connect individual experience and community needs to larger movements and ideologies.",
    distributionRequirements: ["CL", "SB"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "PHIL 140": {
    title: "Ethics and Community",
    description:
      "An examination of contemporary challenges facing democracy as an ideal for the moral life and the moral community.",
    distributionRequirements: ["PD", "CL"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "RELST 180": {
    title: "Religion in American Life",
    description:
      "A social history of Protestant, Catholic, and non-Christian groups in the U.S. context; the role of women and African Americans in various religions is included along with the emergence of sects and denominations, and the religious faiths of immigrant and ethnic populations. The course examines the inherent tension between the Protestant mainstream and the religious diversity resulting from the First Amendment guarantee of religious freedom.",
    distributionRequirements: ["HE", "SB"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENVSC 285": {
    title: "Quantitative Sustainability",
    description:
      "A survey of environmental issues from a quantitative perspective in order to expose students to mathematical tools used in the environmental sciences. Students are asked to make recommendations on issues surrounding climate change, pollution, ecosystem health, land use, population growth, natural resource management, and other current environmental issues. In the process of investigating these topics, students develop a mathematical toolkit for carrying out a variety of calculations, understanding uncertainty, interpreting data, and developing mathematical models to describe economic, social, and environmental systems. .",
    distributionRequirements: ["SP", "QR"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["ENVSC 110"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENVSC 305 ": {
    title: "Environmental GIS I",
    description:
      "An interdisciplinary examination of the theory and techniques used in the mapping and geographic analysis of environmental problems. Environmental research increasingly depends on the ability to gather, analyze, and present spatial data using geographic information systems (GIS). Students are introduced to the use of geospatial technologies through the analysis of environmental case studies. Topics include: vector and raster data models, map registration and coordinate systems, database design, data entry, and editing, GPS data collection, aerial and satellite imagery data sources, query, visualization, and spatial analysis, and cartography. The class includes a weekly three-hour laboratory..",
    distributionRequirements: ["CL", "QR"],
    credits: "4",
    prerequisites: {
      anyof: ["permission from the instructor", "ENVSC 110"],
      allof: [],
    },
    unlocks: ["ENVSC 306"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "ENVSC 306": {
    title: "Environmental GIS II",
    description:
      "An interdisciplinary examination of the theory and techniques used in the advanced mapping and geographic analysis of environmental problems. Students design, execute, and present a semester-long, independent research project whose primary research tool is geographic information systems (GIS) and related technologies. Students are also exposed to advanced topics in GIS including raster-based map algebra, spatial estimation, weighted and fuzzy overlay, network and terrain analysis, modeling and scripting, and data standards and quality. The class includes a weekly three-hour laboratory.",
    distributionRequirements: ["CL", "QR"],
    credits: "4",
    prerequisites: {
      anyof: ["permission from the instructor", "ENVSC 305"],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "GEO 110": {
    title: "Physical Geology",
    description:
      "The study of Earth properties and the dynamics of geologic systems to provide a basic understanding of the resources, environments, and evolution of our planet. The course considers Earth materials, interior structure of the planet, Earth surface processes, landform development, environmental geology, and physical evolution of the Earth. Specific topics include minerals and rocks, plate tectonics, ocean basins, continents, river and groundwater systems, glaciers, volcanism and earthquakes. Laboratory or field work, one period. May be taken after successful completion of Geology 109.",
    distributionRequirements: ["SP", "QR"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["GEO-109"],
    },
    unlocks: [
      "GEO 250",
      "GEO 380",
      "GEO 240",
      "GEO 310",
      "GEO 215",
      "GEO 120",
      "GEO 400",
      "GEO 410",
    ],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "GHS 228": {
    title: "Global Health Data ",
    description:
      "An exploration of publicly available quantitative data related to global health and development from individuals, families, and countries around the world. Students learn how to find, organize, and visualize publicly available data, as well as practice database management, merging, documentation, and visualization with an emphasis on data equity and on the underlying processes by which data are generated by various agencies and organizations. Students investigate the benefits and drawbacks of using publicly available data and gain skills to prepare for independent data analysis",
    distributionRequirements: ["SP", "QR"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "GHS 235": {
    title: "Global Health Ethics",
    description:
      "An introductory ethical study of global health inequalities and our responses to them. Topics include health, justice, and human rights; moral responsibility in global health contexts; power, poverty, and health; ethics and global health governance; the ethics of international medical research; global inequities in access to medical resources; and specific health injustices associated with culture, race, and gender.",
    distributionRequirements: ["PD"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [" GHS 130"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "GHS 321": {
    title: "Epidemiology",
    description:
      "An opportunity to apply epidemiological data to both global health policy and practice, focusing on the determinants of health and patterns and distributions of disease. Topics include the philosophical and ethical dimensions of epidemiology, historical origins, types of study designs, data types and interpretation, and differences between causation and association. Students may not receive credit for both GHS*321 and BIO*321. Credit: Four semester hours",
    distributionRequirements: ["SP", "QR"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["GHS 130 ", "FSGHS 201"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "GHS 354": {
    title: " Medical Anthro/Health in Asia",
    description:
      "Medical Anthropology and Perspectives of Health in Asia-Pacific -- An examination of ethnographic research on health and illness in Asia and the Pacific. Students consider non-western perspectives of health, illness, and bodies through reading medical anthropology works. Topics include infectious disease, chronic disease, addiction, commodification of bodily processes and components, illness related to food and water, and mental health in cultural context. Students learn to draw connections between the health of individuals, population health, and policies created by governing bodies while also developing a sense of how medical anthropological data are interpreted and written.",
    distributionRequirements: ["IP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "HIST 380": {
    title: "Disease/Medicine:Modern History",
    description:
      "An introduction to small-scale, purpose-built physical computational objects which embed sensors, integrate with networks, and process environmental signals. Exploring various industrial architectures, students develop devices that respond to physical stimuli and transmit data across networks to motivate additional device behavior and interactivity while considering human interaction design (HID) and “people-centered” principles that drive device design. During weekly laboratory sessions, students complete projects which focus on industry standards of data transmission and privacy in addition to optimizing device performance for real-time, high-availability applications. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["PD", "HE"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [
        "permission of the instructor",
        "One course in US or European history",
      ],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "PHIL 385": {
    title: "Medical Ethics",
    description:
      "A study of the principles of medical ethics as applied to case studies. After studying the nature and foundations of the principles of medical ethics, students present oral and written analyses of medical cases that pose significant ethical issues.",
    distributionRequirements: [],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "COMM 342": {
    title: "Digital Media and Technology",
    description:
      "An examination of the impacts of digital and social media on online and material cultures. Students explore the role of media technologies in everyday life, focusing particularly on how they shape identities, cultures, and practices. Topics include but are not limited to: the power of media technology industries, built-in biases and privacy issues in artificial intelligence and big data, the normalizing of surveillance, technological innovation and creative activism, and technology as a tool for liberation and oppression. Prerequisite: One 100-level or 200-level COMM course; or permission of the instructor.",
    distributionRequirements: ["PD", "SB"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "DOUBL 600": {
    title: "Sr Project I: Double Major",
    description:
      "Continuation of independent research in software engineering culminating in the development of and release of a computational artifact. Must be taken on the letter-grade basis. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "1 to 4",
    prerequisites: {
      anyof: ["Instructor-approved 580 equivalent", "CMPSC 580"],
      allof: [],
    },
    unlocks: ["DOUBL 600"],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "DOUBL 610": {
    title: "Sr Project II: Double Major",
    description:
      "Independent research in software engineering culminating in the development of a prototype or early draft of a computational artifact. Must be taken on the letter-grade basis. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "1 to 4",
    prerequisites: {
      anyof: [],
      allof: ["DOUBL 600"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 580": {
    title: "Junior Seminar",
    description:
      "An investigation of select topics in computer and information science that prepares students for the completion of a senior project with the purpose of identifying knowledge gaps in the discipline. Students learn how to read scholarly papers, state and motivate research questions, create a software prototype or develop scholarly artifacts to address their findings, and collect and organize evidence for evaluating the outcome of their project. During a weekly laboratory session students use industry-grade technology to gain practical skills in technical writing, the presentation of technical concepts, and the production of an artifact. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [
      "Planning",
      "Idea Development",
      "Professional Development",
      "Literature Review",
      "User Studies",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "Latex",
      },
      {
        iconType: "tool",
        title: "GatorGrader",
      },
      {
        iconType: "tool",
        title: "Python",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "R",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 305": {
    title: "Database Systems",
    description:
      "A study of the application and evaluation of database management systems. Participating in hands-on activities that often require teamwork, students design, implement, and deploy database systems that store interdisciplinary data sets. In addition to learning how to develop and assess interfaces for databases, students study the efficiency and effectiveness of alternative data management systems. During a weekly laboratory session students use industry-grade technology to complete projects, reporting on their results through both written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["QR", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 101"],
    },
    unlocks: [],
    topics: [
      "Teamwork",
      "Queries",
      "Version Control Systems",
      "Databases",
      "Ethics",
      "Data Modeling",
      "Data Storage",
      "Code Review",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "Apache Cassandra",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "SQL",
      },
      {
        iconType: "tool",
        title: "Django",
      },
      {
        iconType: "tool",
        title: "MongoDB",
      },
      {
        iconType: "tool",
        title: "SQLite",
      },
      {
        iconType: "tool",
        title: "Docker",
      },
      {
        iconType: "tool",
        title: "Neo4j",
      },
      {
        iconType: "tool",
        title: "GatorGrader",
      },
      {
        iconType: "tool",
        title: "Python",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 302": {
    title: "Web Design",
    description:
      "An exploration of technologies and data relationships which power modern web applications. Participating in hands-on activities which require teamwork, students build web applications that incorporate the “full stack,” including databases, application programming interfaces (APIs), and public-facing web pages or mobile applications. Students develop a broad knowledge of different development approaches, languages, and design paradigms to learn advantages and disadvantages of technologies and frameworks. During weekly laboratory sessions, students participate in iterative design processes and report progress and technical details through written documents and oral presentations. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: ["IP", "SP"],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 104"],
    },
    unlocks: ["CMPSC 404"],
    topics: [
      "Teamwork",
      "Responsive Design",
      "Iterative Design",
      "Computer Graphics",
      "Networking",
      "User Studies",
      "Version Control Systems",
      "Professional Communication",
      "UI/UX",
      "Design Thinking",
    ],
    technicalTopics: [],
    professionalTopics: [],
    tools: [
      {
        iconType: "tool",
        title: "React",
      },
      {
        iconType: "tool",
        title: "GitHub",
      },
      {
        iconType: "tool",
        title: "11ty",
      },
      {
        iconType: "tool",
        title: "CSS",
      },
      {
        iconType: "tool",
        title: "HTML",
      },
      {
        iconType: "tool",
        title: "Figma",
      },
      {
        iconType: "tool",
        title: "Netlify",
      },
      {
        iconType: "tool",
        title: "JavaScript",
      },
      {
        iconType: "tool",
        title: "Markdown",
      },
    ],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 529": {
    title: "Internship",
    description:
      "Academic study completed in support of an internship experience with a partner institution. An Allegheny faculty member assigns and evaluates the academic work done by the student. May be repeated for credit. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "1-4",
    prerequisites: {
      anyof: [],
      allof: [],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 600": {
    title: "Senior Thesis I",
    description:
      "Individual research under the guidance of a member of the Department's faculty. A project proposal must be submitted to the Department and approved in the semester prior to the semester in which the student intends to register for the course. May be repeated for credit. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "2",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 580"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "CMPSC 610": {
    title: "Senior Project II",
    description:
      "Continuation of independent research in computer science culminating in the development of and release of a computational artifact. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "2",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 600"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "INFM 600": {
    title: "Senior Project I",
    description:
      "Independent research in informatics culminating in the development of a prototype or early draft of a computational artifact. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["CMPSC 580", "Instructor-approved 580 equivalent"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
  "INFM 610": {
    title: "Senior Project II",
    description:
      "Independent research in informatics culminating in the development of a prototype or early draft of a computational artifact. Must be taken on the letter-grade basis. Students are invited to use their own departmentally approved laptop in this course; a limited number of laptops are available for use during class and lab sessions.",
    distributionRequirements: [],
    credits: "4",
    prerequisites: {
      anyof: [],
      allof: ["INFM 600"],
    },
    unlocks: [],
    topics: [],
    technicalTopics: [],
    professionalTopics: [],
    tools: [],
    lab: [],
    learningObjectives: [],
    learningOutcomes: [],
  },
};
