export default {
  absoluteY: 90,
  absoluteX: 76,
  boxes: [
    {
      type: "primaryBox",
      x: 350,
      y: -75,
      strokeColor: "violet5",
      hoverColor: "violet0",
      text: "Data Science Major",
    },
    {
      type: "multiBox",
      x: 300,
      y: 20,
      width: 350,
      height: 650,
      fillColor: "violet5",
      text: "Electives",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 185,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "ECON 203",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 225,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "ECON 241",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 265,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "GHS 223",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 305,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "GHS 228",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 345,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "BIO 321",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 385,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "MATH 320",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 425,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "MATH 346",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 465,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "PSYCH 307",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 505,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "COMM 376",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 545,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 300",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 585,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 302",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 107,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 303",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 147,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 305",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 625,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 350",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 315,
      y: 67,
      width: 321,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 406",
      hoverColor: "violet1",
    },
    {
      type: "multiBox",
      x: -50,
      y: 400,
      width: 290,
      height: 175,
      fillColor: "violet5",
      text: "Project",
    },
    {
      type: "multiBox",
      x: 700,
      y: 20,
      width: 480,
      height: 625,
      fillColor: "violet5",
      text: "Core",
    },

    {
      type: "multiBox",
      x: -50,
      y: 115,
      width: 290,
      height: 175,
      fillColor: "violet5",
      text: "Foundation",
    },

    {
      type: "tertiaryBox",
      x: 950,
      y: 70,
      width: 220,
      fillColor: "blue0",
      strokeColor: "violet3",
      text: "CMPSC 301",
      hoverColor: "violet1",
    },
    {
      type: "multiBox",
      x: 720,
      y: 512,
      width: 445,
      fillColor: "blue5",
      strokeColor: "blue5",
      text: "Effective Communication",
      hoverColor: "blue5",
    },
    {
      type: "tertiaryBox",
      x: 720,
      y: 602,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "COMM 360",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 720,
      y: 560,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "FILM 375",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 950,
      y: 560,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "ENGL 208",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 950,
      y: 602,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "ENGL 210",
      hoverColor: "violet1",
    },
    {
      type: "multiBox",
      x: 720,
      y: 115,
      width: 445,
      fillColor: "blue5",
      strokeColor: "blue5",
      text: "Ethics",
      hoverColor: "blue5",
    },
    {
      type: "tertiaryBox",
      x: 720,
      y: 290,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "PHIL 130 ",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 720,
      y: 250,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "PHIL 140",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 720,
      y: 208,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "PHIL 210 ",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 845,
      y: 165,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "POLSC 140",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 950,
      y: 290,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "PSYCH 162",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 950,
      y: 250,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "RELST 200",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 950,
      y: 208,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "RELST 341",
      hoverColor: "violet1",
    },
    {
      type: "multiBox",
      x: 720,
      y: 335,
      width: 445,
      fillColor: "blue5",
      strokeColor: "blue5",
      text: "Statistics",
      hoverColor: "blue5",
    },
    {
      type: "tertiaryBox",
      x: 720,
      y: 385,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "BIO 385",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 720,
      y: 427,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "ECON 202",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 950,
      y: 385,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "POLSC 489",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 950,
      y: 428,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "MATH 345 ",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 845,
      y: 470,
      width: 220,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "PSYCH 207",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 720,
      y: 70,
      width: 220,
      fillColor: "blue0",
      strokeColor: "violet3",
      text: "CMPSC 405",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: -40,
      y: 450,
      width: 270,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 580",
      hoverColor: "violet1",
    },

    {
      type: "tertiaryBox",
      x: -40,
      y: 490,
      width: 270,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "DS 600",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: -40,
      y: 530,
      width: 270,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "DS 610",
      hoverColor: "violet1",
    },

    {
      type: "tertiaryBox",
      x: -40,
      y: 165,
      width: 270,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 100",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: -40,
      y: 205,
      width: 270,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 101",
      hoverColor: "violet1",
    },

    {
      type: "tertiaryBox",
      x: -40,
      y: 245,
      width: 270,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 105",
      hoverColor: "violet1",
    },
  ],
};
