export default {
  absoluteY: 90,
  absoluteX: 76,
  boxes: [
    {
      type: "primaryBox",
      x: 471,
      y: 140,
      strokeColor: "violet5",
      hoverColor: "violet0",
      text: "Data Science Major",
    },
    {
      type: "multiBox",
      x: 0,
      y: 0,
      width: 243,
      height: 288,
      fillColor: "violet0",
      text: "Electives",
    },
    {
      type: "multiBox",
      x: 110,
      y: 341,
      width: 243,
      height: 153,
      fillColor: "violet0",
      text: "Core",
    },
    {
      type: "multiBox",
      x: 885,
      y: 0,
      width: 243,
      height: 243,
      fillColor: "violet0",
      text: "Project",
    },
    {
      type: "multiBox",
      x: 885,
      y: 296,
      width: 243,
      height: 198,
      fillColor: "violet0",
      text: "Foundation",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 57,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "ECON 203",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 102,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "Usability Test",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 102,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "ECON 241",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 147,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "GHS 223",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 192,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "MATH 320",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 16,
      y: 237,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 300",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 126,
      y: 398,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 301",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 126,
      y: 443,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 405",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 901,
      y: 65,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 580",
      hoverColor: "violet1",
    },

    {
      type: "tertiaryBox",
      x: 901,
      y: 127,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "DS 600",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 901,
      y: 192,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "DS 610",
      hoverColor: "violet1",
    },

    {
      type: "tertiaryBox",
      x: 901,
      y: 353,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 100",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 901,
      y: 398,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 101",
      hoverColor: "violet1",
    },
    {
      type: "tertiaryBox",
      x: 901,
      y: 443,
      width: 211,
      fillColor: "violet0",
      strokeColor: "violet3",
      text: "CMPSC 105",
      hoverColor: "violet1",
    },
  ],
};
