export default {
  absoluteY: 90,
  absoluteX: 76,
  boxes: [
    {
      type: "primaryBox",
      x: 471,
      y: 10,
      strokeColor: "orange5",
      hoverColor: "orange0",
      text: "Informatics Major",
    },
    {
      type: "multiBox",
      x: 443,
      y: 130,
      width: 243,
      height: 198,
      fillColor: "orange0",
      text: "Foundation",
    },
    {
      type: "tertiaryBox",
      x: 459,
      y: 187,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 100",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 459,
      y: 232,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 101",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 459,
      y: 277,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 102",
      hoverColor: "orange1",
    },
    {
      type: "multiBox",
      x: 443,
      y: 397,
      width: 243,
      height: 153,
      fillColor: "orange0",
      text: "Core",
    },
    {
      type: "tertiaryBox",
      x: 459,
      y: 454,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 350",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 459,
      y: 499,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "COMM 342",
      hoverColor: "orange1",
    },
    {
      type: "multiBox",
      x: 806,
      y: 397,
      width: 243,
      height: 380,
      fillColor: "orange0",
      text: "Methods",
    },
    {
      type: "tertiaryBox",
      x: 822,
      y: 454,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "ART 187",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 822,
      y: 499,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "ART 287",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 822,
      y: 544,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 302",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 822,
      y: 589,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "COMM 376",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 822,
      y: 634,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "FILM 171",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 822,
      y: 679,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "FILM 300",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 822,
      y: 724,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "FILM 375",
      hoverColor: "orange1",
    },
    {
      type: "primaryBox",
      x: 471,
      y: 720,
      strokeColor: "orange5",
      hoverColor: "orange0",
      text: "Application Modules",
    },
    {
      type: "multiBox",
      x: 10,
      y: 870,
      width: 243,
      height: 425,
      fillColor: "orange0",
      text: "Humanities Informatics",
    },
    {
      type: "tertiaryBox",
      x: 26,
      y: 927,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "ART 251",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 26,
      y: 972,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "ART 343",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 26,
      y: 1017,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "ENGL 360",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 26,
      y: 1062,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "HIST 170",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 26,
      y: 1107,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "PHIL 140",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 26,
      y: 1152,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "RELST 180",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 26,
      y: 1197,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "RELST 200",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 26,
      y: 1242,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "RELST 341",
      hoverColor: "orange1",
    },
    {
      type: "multiBox",
      x: 300,
      y: 870,
      width: 243,
      height: 380,
      fillColor: "orange0",
      text: "Geoinformatics",
    },
    {
      type: "tertiaryBox",
      x: 316,
      y: 927,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "ENVSC 285",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 316,
      y: 972,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "ENVSC 305",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 316,
      y: 1017,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "ENVSC 306",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 316,
      y: 1062,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "GEO 110",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 316,
      y: 1107,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 304",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 316,
      y: 1152,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 305",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 316,
      y: 1197,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 406",
      hoverColor: "orange1",
    },
    {
      type: "multiBox",
      x: 590,
      y: 870,
      width: 243,
      height: 425,
      fillColor: "orange0",
      text: "Polinformatics",
    },
    {
      type: "tertiaryBox",
      x: 606,
      y: 927,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "COMM 256",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 606,
      y: 972,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "COMM 360",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 606,
      y: 1017,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "POLSC 120",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 606,
      y: 1062,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "POLSC 215",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 606,
      y: 1107,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "POLSC 318",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 606,
      y: 1152,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "POLSC 321",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 606,
      y: 1197,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "POLSC 424",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 606,
      y: 1242,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "PHIL 210",
      hoverColor: "orange1",
    },
    {
      type: "multiBox",
      x: 880,
      y: 870,
      width: 243,
      height: 425,
      fillColor: "orange0",
      text: "Health Informatics",
    },
    {
      type: "tertiaryBox",
      x: 896,
      y: 927,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 300",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 896,
      y: 972,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "COMM 331",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 896,
      y: 1017,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "GHS 228",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 896,
      y: 1062,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "GHS 235",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 896,
      y: 1107,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "GHS 321",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 896,
      y: 1152,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "GHS 354",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 896,
      y: 1197,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "HIST 380",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 896,
      y: 1242,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "PHIL 385",
      hoverColor: "orange1",
    },
    {
      type: "multiBox",
      x: 443,
      y: 1400,
      width: 243,
      height: 198,
      fillColor: "orange0",
      text: "Project",
    },
    {
      type: "tertiaryBox",
      x: 459,
      y: 1457,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "CMPSC 580",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 459,
      y: 1502,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "INFM 600",
      hoverColor: "orange1",
    },
    {
      type: "tertiaryBox",
      x: 459,
      y: 1547,
      width: 211,
      fillColor: "orange0",
      strokeColor: "orange3",
      text: "INFM 610",
      hoverColor: "orange1",
    },
  ],
};
