export default {
  absoluteY: 89,
  absoluteX: 76,
  boxes: [
    {
      type: "primaryBox",
      x: 471,
      y: 72,
      strokeColor: "blue5",
      hoverColor: "blue0",
      text: "SE Major",
    },
    {
      type: "multiBox",
      x: 830,
      y: 233,
      width: 243,
      height: 243,
      fillColor: "blue0",
      text: "Foundation",
    },
    {
      type: "multiBox",
      x: 440,
      y: 233,
      width: 243,
      height: 198,
      fillColor: "blue0",
      text: "Core",
    },
    {
      type: "multiBox",
      x: 50,
      y: 233,
      width: 243,
      height: 243,
      fillColor: "blue0",
      text: "Electives",
    },
    {
      type: "multiBox",
      x: 440,
      y: 510,
      width: 243,
      height: 198,
      fillColor: "blue0",
      text: "Project",
    },
    {
      type: "tertiaryBox",
      x: 846,
      y: 290,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 100",
      hoverColor: "blue1",
    },

    {
      type: "tertiaryBox",
      x: 846,
      y: 335,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 101",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 846,
      y: 380,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 104",
      hoverColor: "blue1",
    },

    {
      type: "tertiaryBox",
      x: 456,
      y: 335,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 203",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 456,
      y: 290,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 302",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 456,
      y: 380,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 404",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 66,
      y: 290,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 303",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 66,
      y: 335,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 305",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 66,
      y: 380,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 400",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 66,
      y: 425,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 403",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 456,
      y: 567,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 580",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 456,
      y: 612,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 600",
      hoverColor: "blue1",
    },
    {
      type: "tertiaryBox",
      x: 456,
      y: 657,
      width: 211,
      fillColor: "blue0",
      strokeColor: "blue3",
      text: "CMPSC 610",
      hoverColor: "blue1",
    },
  ],
};
